apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1 # how many pods should exist at any one time
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world # this is the label that your service.yaml will need to select as its app
    spec:
      containers:
        - name: hello-world
          image: localhost:5000/hello-world
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: cr-regcred